# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install
  displayName: 'Install, Build, Test & Coverage'

- script: |
    npm run coverage
  displayName: 'Test & Coverage'

- script: |
    npm run build
  displayName: 'Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'coverage/lcov-report'
    ArtifactName: 'coverage-report'
    publishLocation: 'Container'
  displayName: 'Publish'